spring:
  application:
    name: course-catalog-service
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5438/courses?serverTimezone=GMT
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual: true
  h2:
    console:
      enabled: true
message: Hello from default profile

#---
#spring:
#  config:
#    activate:
#      on-profile: prod
#message: Hello from prod profile
#
#---
#spring:
#  config:
#    activate:
#      on-profile: non-prod
#message: Hello from prod profile